MODEL:
  NUM_CLASSES: 2
  BOX_HEAD:
    PREDICTOR: 'SSDLiteBoxPredictor'
  BACKBONE:
    NAME: 'mobilenet_v3'
    OUT_CHANNELS: (112, 960, 512, 256, 256, 64)
  PRIORS:
    FEATURE_MAPS: [20, 10, 5, 3, 2, 1]
    STRIDES: [16, 32, 64, 107, 160, 320]
    MIN_SIZES: [60, ]
    MAX_SIZES: [105, ]
    ASPECT_RATIOS: [[2, 3],]
    BOXES_PER_LOCATION: [1,]
INPUT:
  IMAGE_SIZE: 320
DATASETS:
  TRAIN: ("csv_dataset")
  # TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: 'outputs/mobilenet_v3_ssd320_voc0712'
